
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10-browsers
    working_directory: ~/counties-app
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-npm-deps-{{ checksum "package-lock.json" }}
            - v2-npm-deps-
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: v2-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
            - ~/.cache
            - ~/.npm
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Test unit
          command: npm run test:unit
      - run:
          name: Test e2e
          command: npm run test:e2e-headless
      - run:
          name: Build
          command: npm run build
      - run:
          name: Use production project
          command: ./node_modules/.bin/firebase use production
      - run:
          name: Deploy in staging
          command: ./node_modules/.bin/firebase deploy --only hosting  --token "$FIREBASE_TOKEN"

  linter:
    docker:
      - image: circleci/node:10-browsers
    working_directory: ~/counties-app
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-npm-deps-{{ checksum "package-lock.json" }}
            - v2-npm-deps-
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: v2-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
            - ~/.cache
            - ~/.npm
      - run:
          name: Lint
          command: npm run lint

  test_unit:
    docker:
      - image: circleci/node:10-browsers
    working_directory: ~/counties-app
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-npm-deps-{{ checksum "package-lock.json" }}
            - v2-npm-deps-
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: v2-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
            - ~/.cache
            - ~/.npm

      - run:
          name: Test unit
          command: npm run test:unit

  test_e2e:
    docker:
      - image: circleci/node:10-browsers
    working_directory: ~/counties-app
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-npm-deps-{{ checksum "package-lock.json" }}
            - v2-npm-deps-
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: v2-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
            - ~/.cache
            - ~/.npm
      - run:
          name: Test e2e
          command: npm run test:e2e-headless

workflows:
  version: 2
  deploy_production:
    jobs:
      - build:
          filters:
            branches:
              only: master
  lint_and_tests:
    jobs:
      - linter:
          filters:
            branches:
              only: develop
      - test_unit:
          filters:
              branches:
                only: develop
      - test_e2e: 
          filters:
              branches:
                only: develop

